version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.1
    commands:
      - echo 'Login in to the AWS ECR...'
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'pre_build'
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
  build:
    on-failure: ABORT
      commands:
        - echo 'build'
  post_build:
    on-failure: ABORT
      commands:
        - echo 'post_build'

