version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Login in to the AWS ECR...'
      - $(aws ecr get-login-password)|docker login --password-stdin --username AWS ${aws_account).dkr.ecr.us-east-1.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - docker build -t educarte-base-image .
      - docker tag educarte-base-image:latest public.ecr.aws/g8x7s9y4/educarte-base-image:latest
  post_build:
    on-failure: ABORT
    commands:
      - docker push public.ecr.aws/g8x7s9y4/educarte-base-image:latest



#- aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g8x7s9y4
