version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Login in to the AWS ECR...'
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g8x7s9y4
  build:
    on-failure: ABORT
    commands:
      - docker build -t educarte-base-image .
      - docker tag educarte-base-image:latest public.ecr.aws/g8x7s9y4/educarte-base-image:latest
  post_build:
    on-failure: ABORT
    commands:
      - docker push public.ecr.aws/g8x7s9y4/educarte-base-image:latest



#      - docker login -u AWS -p $(aws ecr get-login-password) https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
