version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.1
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'pre_build'
  build:
    on-failure: ABORT
      commands:
        - echo 'build'
  post_build:
    on-failure: ABORT
      commands:
        - echo 'post_build'

